# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20161208_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=256),
        ),
    ]
